/**
 * Forseti contract parity tests — assert the app's TypeScript still says what the C# says.
 *
 * A custom-contract app has TWO implementations of the same rules: the C# every ORK executes,
 * and the app code that tells a human what to expect. Drift between them is silent, and the
 * app's version is the one people believe.
 *
 * These tests read the CONTRACT SOURCE TEXT and compare it to the app's declared values.
 * Regex-against-source is crude and that is the point: no ORK, no .NET runtime, no enclave,
 * no operator approval. It complements `templates/forseti-compile-harness/` — that proves the
 * contract COMPILES; this proves it still says what the app claims it says.
 *
 * Run:  node --test templates/forseti-parity-tests/
 * (No dependencies. Uses node:test + node:assert.)
 *
 * Configure via ./parity.config.mjs — do not edit this file.
 */

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import config from './parity.config.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = process.env.PARITY_ROOT ? resolve(process.env.PARITY_ROOT) : process.cwd();
const contractFile = resolve(ROOT, config.contractPath);

const NINE_BUILTIN_MODELS = [
  'Offboard:1', 'RotateVRK:1', 'TestInit:1', 'Policy:1', 'HederaTx:1',
  'PolicyEnabledEncryption:1', 'PolicyEnabledDecryption:1', 'ServerCert:1', 'AttestationUnit:1',
];

// Blocked in the Forseti sandbox. These COMPILE fine and fail IL vetting at upload with
// BadPolicy.ForbiddenCall, so the compiler cannot catch them and a grep is the only local check.
const BLOCKED = [
  'System\\.IO', 'System\\.Net', 'System\\.Threading', 'System\\.Reflection',
  'System\\.Diagnostics', 'System\\.Console',
  'DateTime\\.Now', 'DateTime\\.UtcNow', 'Guid\\.NewGuid', 'new Random', 'Random\\.Shared',
];

describe('contract source', () => {
  test('the contract file exists and is not empty', () => {
    assert.ok(
      existsSync(contractFile),
      `contractPath '${config.contractPath}' not found (resolved: ${contractFile}). ` +
      `Set PARITY_ROOT if you run this from outside the repo root.`,
    );
    assert.ok(readFileSync(contractFile, 'utf8').trim().length > 0, 'contract file is empty');
  });
});

const CONTRACT = existsSync(contractFile) ? readFileSync(contractFile, 'utf8') : '';

describe('entry shape — what the ORK looks for', () => {
  test('uses the Ork.Forseti.Sdk namespace', () => {
    assert.match(CONTRACT, /using\s+Ork\.Forseti\.Sdk\s*;/,
      'missing `using Ork.Forseti.Sdk;` (AP-56)');
  });

  test('a class implements IAccessPolicy', () => {
    assert.match(CONTRACT, /class\s+\w+\s*:\s*IAccessPolicy/,
      'no class implements IAccessPolicy — BadPolicy.EntryTypeNotFound');
  });

  test('does not call PolicyDecision.Approve (it does not exist)', () => {
    assert.doesNotMatch(CONTRACT, /PolicyDecision\.Approve/,
      'PolicyDecision.Approve() does not exist; use PolicyDecision.Allow()');
  });
});

describe('sandbox constraints', () => {
  test('references no namespace or call the Forseti sandbox blocks', () => {
    // This scans the WHOLE file, COMMENTS INCLUDED, deliberately.
    //
    // Stripping comments first would be more convenient and is the wrong trade: a naive
    // stripper treats the `//` inside a string literal as a comment start and can swallow the
    // rest of the line, hiding a REAL call. A false positive costs you one reworded comment;
    // a false negative costs an operator approval and a BadPolicy.ForbiddenCall at upload.
    //
    // So if a hit is in a doc comment: REWORD THE COMMENT. Do not weaken the scan.
    const lines = CONTRACT.split('\n');
    const hits = [];
    for (const pattern of BLOCKED) {
      const re = new RegExp(pattern);
      lines.forEach((line, i) => {
        if (re.test(line)) {
          hits.push({
            pattern: pattern.replace(/\\/g, ''),
            line: i + 1,
            text: line.trim().slice(0, 100),
            looksLikeComment: /^\s*(\/\/|\*|\/\*)/.test(line),
          });
        }
      });
    }

    if (hits.length === 0) return;

    const report = hits
      .map((h) => `  line ${h.line}: ${h.pattern}${h.looksLikeComment ? '  [in a COMMENT — reword it]' : '  <-- REAL CALL SITE'}\n      ${h.text}`)
      .join('\n');
    const real = hits.filter((h) => !h.looksLikeComment).length;

    assert.fail(
      `${hits.length} blocked reference(s) found — these compile fine and fail IL vetting at ` +
      `upload with BadPolicy.ForbiddenCall (${real} outside comments):\n${report}\n` +
      `  Time must come from Cryptide.Tools.Utils.GetEpochSeconds(), never DateTime.UtcNow.`,
    );
  });
});

describe('context isolation — ctx.Data lives only in ValidateData', () => {
  const methodBody = (name) => {
    const start = CONTRACT.indexOf(`PolicyDecision ${name}`);
    if (start === -1) return null;
    // Walk braces from the first { after the signature to find the method body.
    const open = CONTRACT.indexOf('{', start);
    if (open === -1) return null;
    let depth = 0;
    for (let i = open; i < CONTRACT.length; i++) {
      if (CONTRACT[i] === '{') depth++;
      else if (CONTRACT[i] === '}' && --depth === 0) return CONTRACT.slice(open, i + 1);
    }
    return CONTRACT.slice(open);
  };

  for (const name of config.dataIsolation ?? []) {
    test(`${name} does not read ctx.Data`, () => {
      const body = methodBody(name);
      if (body === null) {
        // Not implemented is fine — only ValidateData is mandatory in practice.
        return;
      }
      assert.doesNotMatch(
        body, /ctx\s*\.\s*Data\b/,
        `${name} reads ctx.Data. The contexts are DISJOINT — this compiles in an editor and ` +
        `fails on the ORK with CS1061 (VmHost.CompileFailed), after an approval has been spent. ` +
        `Capture in ValidateData, compare here.`,
      );
    });
  }
});

describe('fail-closed guard', () => {
  test('a Deny exists for the capture flag', (t) => {
    if (!config.failClosedFlag) return t.skip('failClosedFlag not configured');
    const flag = config.failClosedFlag.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const re = new RegExp(`${flag}[\\s\\S]{0,200}Deny`);
    assert.match(
      CONTRACT, re,
      `no Deny guarded by ${config.failClosedFlag}. "The check did not run" can only mean refuse; ` +
      `a null-tolerant comparison silently turns the strongest check in the contract into no check.`,
    );
  });
});

describe('identity binding — the vuid, never a JWT subject', () => {
  test('compares the doken identity', (t) => {
    if (!config.identity?.mustMatch) return t.skip('identity.mustMatch not configured');
    assert.match(CONTRACT, new RegExp(config.identity.mustMatch),
      `expected the contract to compare DokenDto.UserId (the vuid)`);
  });

  for (const pattern of config.identity?.mustNotMatch ?? []) {
    test(`does not reference ${pattern.replace(/\\/g, '')}`, () => {
      assert.doesNotMatch(
        CONTRACT, new RegExp(pattern),
        `a doken carries NO OIDC subject — DokenDto.UserId IS the vuid. A contract comparing a ` +
        `subject denies every request (AP-66).`,
      );
    });
  }
});

describe('policy parameters', () => {
  const declared = [...CONTRACT.matchAll(/\[PolicyParam\([^)]*\)\]\s*public\s+[\w<>?\[\]]+\s+(\w+)\s*\{/g)]
    .map((m) => m[1]);

  test('the contract declares at least one [PolicyParam]', (t) => {
    if (!config.suppliedParams) return t.skip('suppliedParams not configured');
    assert.ok(declared.length > 0, 'no [PolicyParam] properties found — check the regex/prefix');
  });

  test('declared params EQUAL the params the policy supplies', (t) => {
    if (!config.suppliedParams) return t.skip('suppliedParams not configured');
    const supplied = config.suppliedParams.map(([k]) => k);
    assert.deepEqual(
      [...declared].sort(), [...supplied].sort(),
      `mismatch between [PolicyParam] properties and the params the policy sends. A required ` +
      `param the policy never supplies fails at request time, ON THE ORKS, after an approval.\n` +
      `  declared in contract: ${[...declared].sort().join(', ')}\n` +
      `  supplied by policy  : ${[...supplied].sort().join(', ')}`,
    );
  });

  test('numeric ladder params are strictly increasing', (t) => {
    if (!config.strictlyIncreasingParams) return t.skip('strictlyIncreasingParams not configured');
    const byKey = new Map(config.suppliedParams ?? []);
    const values = config.strictlyIncreasingParams.map((k) => {
      const raw = byKey.get(k);
      assert.ok(raw !== undefined, `strictlyIncreasingParams names '${k}', which is not supplied`);
      const n = Number(raw);
      assert.ok(Number.isFinite(n), `param '${k}' is not numeric: ${raw}`);
      return [k, n];
    });
    for (let i = 1; i < values.length; i++) {
      assert.ok(
        values[i][1] > values[i - 1][1],
        `ladder not strictly increasing: ${values[i - 1][0]}=${values[i - 1][1]} then ` +
        `${values[i][0]}=${values[i][1]}. A misordered ladder makes the contract deny EVERY request.`,
      );
    }
  });
});

describe('policy identity', () => {
  test('modelId is a registered id or the BasicCustom<..> form', (t) => {
    if (!config.modelId) return t.skip('modelId not configured');
    const ok = NINE_BUILTIN_MODELS.includes(config.modelId)
      || /^BasicCustom<.+>:BasicCustom<.+>$/.test(config.modelId);
    assert.ok(
      ok,
      `modelId '${config.modelId}' is not one of the nine built-ins and does not match ` +
      `BasicCustom<Name>:BasicCustom<Version>. It is a registry key checked on every ORK ` +
      `AFTER an operator approval has been spent (AP-65).`,
    );
  });

  test('does not borrow AttestationUnit:1', (t) => {
    if (!config.modelId) return t.skip('modelId not configured');
    assert.notEqual(
      config.modelId, 'AttestationUnit:1',
      `AttestationUnit:1 carries IGA governance changes and renders in the enclave as ` +
      `"Governance change" — it is the wrong card to put in front of an approver.`,
    );
  });
});

describe('wire-format parity', () => {
  test('contract field indices match the encoder', (t) => {
    if (!config.wire?.fields) return t.skip('wire.fields not configured');
    const prefix = config.wire.prefix ?? 'F_';
    const re = new RegExp(`private\\s+const\\s+int\\s+${prefix}(\\w+)\\s*=\\s*(\\d+)\\s*;`, 'g');
    const fromSource = {};
    for (const m of CONTRACT.matchAll(re)) fromSource[m[1]] = Number(m[2]);
    assert.ok(Object.keys(fromSource).length > 0,
      `no '${prefix}<NAME> = <n>' constants found — check wire.prefix`);
    assert.deepEqual(
      fromSource, config.wire.fields,
      `wire field indices disagree. The contract would validate bytes the encoder did not write ` +
      `there — the signature covers bytes nobody checked.`,
    );
  });

  test('field count agrees', (t) => {
    if (!config.wire?.countConstant || config.wire.countValue == null) {
      return t.skip('wire.countConstant/countValue not configured');
    }
    const m = CONTRACT.match(
      new RegExp(`private\\s+const\\s+int\\s+${config.wire.countConstant}\\s*=\\s*(\\d+)\\s*;`),
    );
    assert.ok(m, `constant '${config.wire.countConstant}' not found in the contract`);
    assert.equal(Number(m[1]), config.wire.countValue,
      `field-count mismatch — surfaces as "Expected N fields, found M" on the ORKs`);
  });
});

describe('custom source assertions', () => {
  for (const a of config.sourceAssertions ?? []) {
    test(a.name, () => {
      const re = new RegExp(a.pattern);
      if (a.shouldMatch === false) assert.doesNotMatch(CONTRACT, re, a.message ?? '');
      else assert.match(CONTRACT, re, a.message ?? '');
    });
  }
});

describe('deployed policy freshness', () => {
  test('deployed contractId equals a fresh hash of the source', (t) => {
    if (!config.deployedPolicyPath) return t.skip('deployedPolicyPath not configured');
    const p = resolve(ROOT, config.deployedPolicyPath);
    if (!existsSync(p)) return t.skip(`no deployed policy at ${config.deployedPolicyPath} yet`);

    const stored = JSON.parse(readFileSync(p, 'utf8'));
    const deployed = stored[config.deployedPolicyContractIdKey ?? 'contractId'];
    if (!deployed) return t.skip('deployed policy has no contractId recorded');

    const fresh = createHash('sha512').update(readFileSync(contractFile, 'utf8'), 'utf8')
      .digest('hex').toUpperCase();

    assert.match(fresh, /^[0-9A-F]{128}$/);
    assert.equal(
      String(deployed).toUpperCase(), fresh,
      `The deployed policy does NOT describe this contract. Any edit — even a comment — changes ` +
      `the SHA-512 and invalidates the policy. Redeploy (costs a fresh enclave approval), or ` +
      `restore the source.\n  deployed: ${String(deployed).slice(0, 24)}…\n  source  : ${fresh.slice(0, 24)}…`,
    );
  });
});
